services:

  prometheus:
    image: prom/prometheus:v3.5.0
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - "D:/Learning/Backend/Microservice/Food Delivery App/Food App Backend/observability/provisioning/prometheus.yml:/etc/prometheus/prometheus.yml"

  grafana:
    image: grafana/grafana:9.5.2
    container_name: grafana
    ports:
      - "3005:3000"
    restart: unless-stopped
    volumes:
      - "D:/Learning/Backend/Microservice/Food Delivery App/Food App Backend/observability/grafana/datasources:/etc/grafana/provisioning/datasources"

  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml