
server:
  port: 8078

eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/

loki:
  url: http://localhost:3100/loki/api/v1/push