spring:
  application:
    name: config-server
  profiles:
    active: local
  cloud:
    config:
      server:
        git:
          uri: https://github.com/deeparishi/order-my-meal-config-repo.git
          username: deeparishi
          password:
          default-label: main
          clone-on-start: true
          force-pull: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org.springframework.cloud.config.server: DEBUG
    org.eclipse.jgit: DEBUG