server:
  port: 8090

eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://localhost:8000/eureka/
  server:
    enable-self-preservation: false

loki:
  url: http://localhost:3100/loki/api/v1/push

management:
  endpoints:
    enabled: true
    web:
      exposure:
        include: health,info,prometheus
  metrics:
    export:
      prometheus:
        enabled: true