spring:
  application:
    name: payment-service
  profiles:
    active: local

encryption:
  key: cavin*info*tech@
  cipherMode: AES/ECB/PKCS5Padding

management:
  endpoints:
    enabled: true
    web:
      exposure:
        include: health,info,prometheus
  metrics:
    export:
      prometheus:
        enabled: true

feign:
  client:
    config:
      api-gateway:
        connectTimeout: 5000
        readTimeout: 5000

resilience4j.retry:
  configs:
    default:
      maxAttempts: 3
      waitDuration: 500
      enableExponentialBackoff: true
      exponentialBackoffMultiplier: 2
      ignoreExceptions:
        - java.lang.NullPointerException
      retryExceptions:
        - java.util.concurrent.TimeoutException

resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 2
      failureRateThreshold: 50
      waitDurationInOpenState: 10000